find_path(LibPLYXX_INCLUDE_DIR libplyxx.h)
find_library(LibPLYXX_LIBRARY NAMES libplyxx)
if (LibPLYXX_INCLUDE_DIR AND LibPLYXX_LIBRARY)
  set(LibPLYXX_FOUND TRUE)
endif ()

if (LibPLYXX_FOUND)
  if (NOT LibPLYXX_FIND_QUIETLY)
    message(STATUS "Found LibPLYXX: ${LibPLYXX_LIBRARY}")
  endif ()
else ()
  if (LibPLYXX_FIND_REQUIRED)
    message(FATAL_ERROR "Could not find LibPLYXX")
  endif ()
endif ()
