find_path(Mitobrevno_INCLUDE_DIR mitobrevno.h)
find_library(Mitobrevno_LIBRARY NAMES mitobrevno)
if (Mitobrevno_INCLUDE_DIR AND Mitobrevno_LIBRARY)
  set(Mitobrevno_FOUND TRUE)
endif ()

if (Mitobrevno_FOUND)
  if (NOT Mitobrevno_FIND_QUIETLY)
    message(STATUS "Found Mitobrevno: ${Mitobrevno_LIBRARY}")
  endif ()
else ()
  if (Mitobrevno_FIND_REQUIRED)
    message(FATAL_ERROR "Could not find Mitobrevno")
  endif ()
endif ()
