find_path(Plytapus_INCLUDE_DIR plytapus.h)
find_library(Plytapus_LIBRARY NAMES plytapus)
if (Plytapus_INCLUDE_DIR AND Plytapus_LIBRARY)
  set(Plytapus_FOUND TRUE)
endif ()

if (Plytapus_FOUND)
  if (NOT Plytapus_FIND_QUIETLY)
    message(STATUS "Found Plytapus: ${Plytapus_LIBRARY}")
  endif ()
else ()
  if (Plytapus_FIND_REQUIRED)
    message(FATAL_ERROR "Could not find Plytapus")
  endif ()
endif ()
